import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';

const dist = resolve('dist');

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    const s = statSync(path);
    if (s.isDirectory()) yield* walk(path);
    else if (path.endsWith('.html') || path.endsWith('.xml')) yield path;
  }
}

let errors = 0;
const files = new Set();

for (const path of walk(dist)) {
  const rel = path.slice(dist.length).replace(/\\/g, '/');
  files.add(rel);
  if (rel.endsWith('/index.html')) files.add(rel.replace(/\/index\.html$/, '/'));
}

for (const path of walk(dist)) {
  const rel = path.slice(dist.length).replace(/\\/g, '/');
  const html = readFileSync(path, 'utf-8');
  const hrefs = [...html.matchAll(/href="([^"]+)"/g)].map(m => m[1]);
  for (const href of hrefs) {
    if (href.startsWith('http') || href.startsWith('#') || href.startsWith('mailto:') || href.startsWith('data:')) continue;
    let target = href;
    if (target.startsWith('/')) {
      // absolute
    } else {
      const dir = dirname(rel);
      target = resolve('/', dir, target).replace(/\\/g, '/');
    }
    if (target.endsWith('/')) target = target + 'index.html';
    // Astro static output may also create /page.html for /page/index.html depending on config
    // For our default static output, /articles/ -> /articles/index.html, /articles -> /articles.html isn't generated by default
    const exists = files.has(target) || files.has(target + '/index.html') || files.has(target.replace(/\/$/, '') + '.html');
    if (!exists) {
      console.error(`❌ ${rel} → broken link: ${href}`);
      errors++;
    }
  }
}

if (errors) {
  console.error(`\n${errors} broken link(s) found`);
  process.exit(1);
}
console.log('✅ All internal links look good');
